--creating sequence for hotel_id
CREATE SEQUENCE hotel_id_seq START WITH 1 INCREMENT BY 1;

--creating procedure using pl sql for hotel data insertion in hotel table 
CREATE OR REPLACE PROCEDURE insert_hotel_data (
    p_hotel_name  IN  VARCHAR2,
    p_address     IN  VARCHAR2,
    p_phone       IN  VARCHAR2
) AS
    v_hotel_id    NUMBER;
BEGIN
    SELECT hotel_id_seq.NEXTVAL INTO v_hotel_id FROM DUAL;
    
    INSERT INTO hotel (hotel_id, hotel_name, hotel_address, hotel_phone)
    VALUES (v_hotel_id, p_hotel_name, p_address, p_phone);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Data inserted successfully.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END insert_hotel_data;
/

-- example of function call
BEGIN
    insert_hotel_data(
        p_hotel_name  => 'Hotel XYZ',
        p_address     => '456 Elm Street',
        p_phone       => '555-5678'
    );
END;
/




-- Creating Sequence for room_id
CREATE SEQUENCE room_seq START WITH 1 INCREMENT BY 1 MAXVALUE 999999 ORDER;

-- Creating a procedure to add a new ROOM
CREATE OR REPLACE PROCEDURE add_room(r_id number,
                                     h_id number,
                                     r_price number,
                                     r_size varchar2,
                                     r_capacity number
                                     ) IS
unique_exception EXCEPTION;  
PRAGMA EXCEPTION_INIT(unique_exception, -00001);
                                            
BEGIN
    
    INSERT INTO room VALUES(room_seq.nextval, h_id, r_price, r_size, r_capacity);

    EXCEPTION
        WHEN unique_exception THEN
            dbms_output.put_line(' The room size has to be one of the following: small, medium, large');
    
END;

-- Example of calling the procedure
BEGIN
    add_room(
        r_id => NULL, -- This will be ignored as the room_id is generated by the sequence
        h_id => 1, -- Hotel ID of the room
        r_price => 100, -- Price of the room
        r_size => 'medium', -- Size of the room
        r_capacity => 2 -- Capacity of the room
    );
END;
/

-- Creating Sequence for guest_id
CREATE SEQUENCE guest_seq START WITH 1 INCREMENT BY 1 MAXVALUE 999999 ORDER;

-- Creating a procedure to add a new GUEST
CREATE OR REPLACE PROCEDURE insert_guest(
    g_name IN VARCHAR2,
    g_phone IN VARCHAR2,
    g_email IN VARCHAR2
) AS
BEGIN
    INSERT INTO guest (guest_id, guest_name, guest_phone, guest_email)
    VALUES (guest_seq.nextval, g_name, g_phone, g_email);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Guest inserted successfully.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END insert_guest;
/

-- Example of calling the procedure
BEGIN
    insert_guest(
        g_name => 'Alice Smith',
        g_phone => '555-5678',
        g_email => 'alice@example.com'
    );
END;
/




-- Creating Sequence for booking_id
CREATE SEQUENCE book_seq START WITH 1 INCREMENT BY 1 MAXVALUE 999999 ORDER;


-- Creating a procedure to book a reservation
CREATE OR REPLACE PROCEDURE book_room(r_id number,
                                      g_id number,
                                      b_id number,
                                      b_invoice number
                                      ) IS
                                                                                         
foreign_exception EXCEPTION;                  
PRAGMA EXCEPTION_INIT(foreign_exception, -02291);       
                                                
BEGIN

    INSERT INTO room_reservation VALUES(r_id, g_id, b_id, b_invoice);
    
    EXCEPTION
        WHEN no_data_found THEN
                    dbms_output.put_line(g_id || ' Is not a registered guest, Kindly registed the guest before booking a room');
           
        WHEN foreign_exception THEN
         dbms_output.put_line(' There is a foreign key constraint, Kindly consider the values');

END;


DECLARE
    -- Declare variables to pass as parameters to the procedure
    v_r_id number := 2; 
    v_g_id number := 2; 
    v_b_id number := book_seq.NEXTVAL; 
    v_b_invoice number := 789; 
BEGIN
    book_room(v_r_id, v_g_id, v_b_id, v_b_invoice);
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
     
        dbms_output.put_line('An error occurred: ' || SQLERRM);
        ROLLBACK;
END;



-- Creating Sequence for event_id
CREATE SEQUENCE event_seq START WITH 1 INCREMENT BY 1 MAXVALUE 999999 ORDER;


-- Creating a procedure to add a new event
CREATE OR REPLACE PROCEDURE add_event(e_id number,
                                      e_name varchar2
                                      ) IS
                                               

BEGIN

    INSERT INTO event VALUES(event_seq.nextval, e_name);
    
END;

DECLARE
    
    v_e_name varchar2(100) := 'Example Event Name';
BEGIN
  
    add_event(NULL, v_e_name); 

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('An error occurred: ' || SQLERRM);
        ROLLBACK;
END;



-- Cancelling a room reservation
CREATE OR REPLACE PROCEDURE cancel_room_reservation(r_id number,
                                                    g_id number,
                                                    b_id number
                                                    ) IS
                                                                                       
                                                                     
BEGIN

    DELETE FROM room_reservation WHERE room_id = r_id AND guest_id = g_id AND booking_id = b_id;
    
END;


set serveroutput on;
DECLARE
    v_r_id number := 2; --  room ID
    v_g_id number := 2; --  guest ID
    v_b_id number := 2; --  booking ID
BEGIN
    cancel_room_reservation(v_r_id, v_g_id, v_b_id);
     COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('An error occurred: ' || SQLERRM);
        ROLLBACK;
END;



--------------------------------------------------FIND HOTEL---------------------------------------------
-- Creating a function to retrieve a hotel
CREATE OR REPLACE FUNCTION find_hotel(h_id number) RETURN varchar2 IS

v_h_id hotel.hotel_id%type;
v_h_name hotel.hotel_name%type;
v_h_address hotel.hotel_address%type;
v_h_phone hotel.hotel_phone%type;
hotel_details varchar2(150);

BEGIN

    SELECT hotel_id,
           hotel_name,
           hotel_address,
           hotel_phone
    INTO v_h_id,
         v_h_name,
         v_h_address,
         v_h_phone
    FROM hotel
    WHERE hotel_id = h_id;
    
    hotel_details := 'Hotel name is  ' || v_h_name || ', The address is  ' || v_h_address || ' and the phone number is ' || v_h_phone;
    RETURN hotel_details;
    
END;

-- Creating a function to retrieve a hotel
set serveroutput on;
DECLARE
    v_hotel_id NUMBER := 3; --  hotel ID
    v_hotel_details VARCHAR2(150);
BEGIN
   
    v_hotel_details := find_hotel(v_hotel_id);
    dbms_output.put_line('Hotel details: ' || v_hotel_details);
END;
/


--------------------------------------------------FIND ROOM---------------------------------------------
-- Creating a function to retrieve room details
CREATE OR REPLACE FUNCTION find_room(r_id number) RETURN varchar2 IS


v_room_id room.room_id%type;
v_hotel_id room.hotel_id%type;
v_room_size room.room_size%type;
v_room_capacity room.room_capacity%type;
room_details varchar2(150);

BEGIN

    SELECT room_id,
           hotel_id,
           room_size,
           room_capacity
    INTO v_room_id,
         v_hotel_id,
         v_room_size,
         v_room_capacity
    FROM room
    WHERE room_id = r_id;
    
    room_details := 'Room ID is  ' ||v_room_id || ' That is in hotel ID  ' || v_hotel_id || ' The room size is  ' || v_room_size || ' and the capacity is  ' || v_room_capacity;
    RETURN room_details;
    
END;

set serveroutput on
DECLARE
    v_room_id NUMBER := 3; --  room ID
    v_room_details VARCHAR2(150);
BEGIN
    v_room_details := find_room(v_room_id);
        dbms_output.put_line('Room details: ' || v_room_details);
END;
/

--------------------------------------------------FIND ROOM RESERVATION---------------------------------------------
-- Creating a function to retrieve room_reservation details
CREATE OR REPLACE FUNCTION find_reservation(b_id number) RETURN varchar2 IS

v_room_id room_reservation.room_id%type;
v_guest_id room_reservation.guest_id%type;
v_booking_id room_reservation.booking_id%type;
v_booking_invoice room_reservation.booking_invoice%type;
reservation_details varchar2(150);

BEGIN

    SELECT room_id,
           guest_id,
           booking_id,
           booking_invoice
    INTO v_room_id,
         v_guest_id,
         v_booking_id,
         v_booking_invoice
    FROM room_reservation
    WHERE booking_id = b_id;
    
    reservation_details := 'Room ' || v_room_id || ' Is reserved for ' || v_guest_id || ' with a booking ID ' || v_booking_id || ' and a booking invoice of approx. ' || v_booking_invoice;
    RETURN reservation_details;
    
END;

set serveroutput on;
DECLARE
    v_booking_id NUMBER := 2; --  booking ID
    v_reservation_details VARCHAR2(150);
BEGIN
    v_reservation_details := find_reservation(v_booking_id);
        dbms_output.put_line('Reservation details: ' || v_reservation_details);
END;
/


--------------------------------------------------FIND EVENT---------------------------------------------
-- Creating a function to retrieve event details
CREATE OR REPLACE FUNCTION find_event(e_id number) RETURN varchar2 IS


v_event_id event.event_id%type;
v_event_name event.event_name%type;
event_details VARCHAR2(150);

BEGIN

    SELECT event_id,
           event_name
    INTO v_event_id,
         v_event_name
    FROM event
    WHERE event_id = e_id;
    
    event_details := 'Event id ' || v_event_id || ' is  ' || v_event_name;
    RETURN event_details;

END;

-- Calling the function to retrieve event details for a specific event ID
set serveroutput on;
DECLARE
    v_event_id_to_find number := 1; --event ID
    v_event_details varchar2(150);
BEGIN
    v_event_details := find_event(v_event_id_to_find);
    dbms_output.put_line(v_event_details);
END;
/




---------------------------------------FIND EVENT RESERVATION---------------------------------------------
-- Creating a function to retrieve event reservation details
CREATE OR REPLACE FUNCTION find_event_reservation(e_id number) RETURN varchar2 IS

v_event_id event_in_hotel.event_id%type;
v_guest_id event_in_hotel.guest_id%type;
v_reserv_id event_in_hotel.reserv_id%type;
v_start_date event_in_hotel.start_date%type;
v_end_date event_in_hotel.end_date%type;
v_event_invoice event_in_hotel.event_invoice%type;
event_reservation_details varchar2(250);

BEGIN

    SELECT event_id,
           guest_id,
           reserv_id,
           start_date,
           end_date,
           event_invoice
    INTO    v_event_id,
            v_guest_id,
            v_reserv_id,
            v_start_date,
            v_end_date,
            v_event_invoice
    FROM event_in_hotel
    WHERE event_id = e_id;
    
    event_reservation_details := 'Event  ' || v_event_id || ' which is booked by guest ID ' || v_guest_id || ' with a reservation id ' || v_reserv_id || ' has started on ' || v_start_date ||
                                              ' and an end date of ' || v_end_date || ' and its invoice is ' || v_event_invoice;
    RETURN event_reservation_details;
    
END;

-- Calling the function to retrieve event reservation details for a specific event ID
set serveroutput on;
DECLARE
    v_event_id_to_find number := 1; -- event ID
    v_reservation_details varchar2(250);
BEGIN
    v_reservation_details := find_event_reservation(v_event_id_to_find);
    dbms_output.put_line(v_reservation_details);
END;
/

select * from event_in_hotel;






